<?php
require_once('Sections.admin.php');
require_once('NewsLine.admin.php');
require_once('Articles.admin.php');
require_once('Storefront.admin.php');
require_once('Index_properties.admin.php');
require_once('Index_Search.admin.php');
require_once('Setup.admin.php');
require_once('PriceImport.admin.php');
require_once('PriceExport.admin.php');
require_once('Stat.admin.php');
require_once('Orders.admin.php');
require_once('Users.admin.php');
require_once('Login.admin.php');
require_once('Sitemap.admin.php');
require_once('Comments.admin.php');
require_once('Currency.admin.php');
require_once('Import.admin.php');
require_once('Polls.admin.php');
require_once('Contacts.admin.php');
require_once('Faq.admin.php');
require_once('Announcement.admin.php');
require_once('Payment.admin.php');
require_once('Gallery.admin.php');
require_once('Mapsite.admin.php');
require_once('Links.admin.php');
?>