<?PHP

require_once('Widget.class.php');
#SERVICES
require_once('StaticPage.class.php');
require_once('ExternalLink.class.php');
require_once('NewsLine.class.php');
require_once('Articles.class.php');
require_once('Storefront.class.php');
//require_once('Search.class.php');
require_once('Basket.class.php');
require_once('Login.class.php');
//require_once('Contacts.class.php');
//require_once('Prise_List.class.php');
require_once('Registration.class.php');
require_once('MainPage.class.php');
//require_once('Orders.class.php');
//require_once('ProductFoto.class.php');
require_once('Poll.class.php');
require_once('Faq.class.php');
require_once('protect/kcaptcha.php');
//require_once('Announcement.class.php');
//require_once('Documents.class.php');
//require_once('Deliveries.class.php');
require_once('Gallery.class.php');
require_once('Mapsite.class.php');
//require_once('Links.class.php');
//require_once('prcy.php');
//require_once('webpage.php');
?>